#!/bin/sh

# TODO: need to add logic to add counter specific to user
ORG_MSG=$(cat $1)
ORG_COUNT=$(cat tools/git-hooks/aks-commit.couter)

CURR_COUNT=$((ORG_COUNT + 1))
echo $CURR_COUNT >githooks/aks-commit.couter

while ((${#CURR_COUNT} < 6)); do
    CURR_COUNT="0$CURR_COUNT"
done

AMEND_COMMIT_MSG="AKS-$CURR_COUNT: $ORG_MSG"
echo $AMEND_COMMIT_MSG

echo $AMEND_COMMIT_MSG >$1
